#theme: just-the-docs
remote_theme: petersenpeter/just-the-docs
# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/
# Aux links for the upper right navigation
aux_links:
  "Code on GitHub":
    - "//github.com/petersenpeter/CellExplorer"
  "Manuscript on bioRxiv":
    - "https://www.biorxiv.org/content/10.1101/2020.05.07.083436v1"

title: CellExplorer
description: "Matlab GUI and standardized pipeline for exploring and classifying spike sorted single units acquired using extracellular electrodes."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cellexplorer.org" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo6.png"

# Enable or disable the site search
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2019-2020 Peter Petersen. Theme: <a href=\"https://github.com/pmarsceill/just-the-docs\" target=\"_blank\">Just the Docs</a>."

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-166238697-1

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false